// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCeBXPf8Gni3_AfG6WP8oFZSel3E6mzKkU",
    authDomain: "vetementia-13017.firebaseapp.com",
    projectId: "vetementia-13017",
    storageBucket: "vetementia-13017.firebasestorage.app",
    messagingSenderId: "734784983658",
    appId: "1:734784983658:web:8565cd4abe9d1644637013",
    measurementId: "G-QQ4G3EE440"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyACYXnVJEg5KgIBC_1hOL0MI-SgWnjRiK0",
    appId: "1:734784983658:android:f26f6e91de5752c4637013",
    messagingSenderId: "734784983658",
    projectId: "vetementia-13017",
    storageBucket: "vetementia-13017.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCmowDYfw4BGHgzOrjhHysxRglG7gvg9oA",
    appId: "1:734784983658:ios:3799aba04b061cad637013",
    messagingSenderId: "734784983658",
    projectId: "vetementia-13017",
    storageBucket: "vetementia-13017.firebasestorage.app",
    iosBundleId: "com.nizar",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-HqnhA5gMS4hZN_Kj-pKLU27NLR1zTo',
    appId: '1:124193868831:ios:52261dd31dfe16fa88d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    storageBucket: 'vetementia.firebasestorage.app',
    iosBundleId: 'com.nizar.vetementIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFMLDrHe2MiSC9UpyTZcGsej1_BqLLneo',
    appId: '1:124193868831:web:e75ca400086e1a7b88d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    authDomain: 'vetementia.firebaseapp.com',
    storageBucket: 'vetementia.firebasestorage.app',
  );
}
